/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View, Button } from 'react-native';
import Crowdin from 'react-native-crowdin';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--',
    androidMessage: 'before get from Android'
  };
  componentDidMount() {
    Crowdin.initWithHashString('42dae90f4877fb6aba2acf876j9', 'en', (message) => {
      console.log(Crowdin.getResources)
      this.setState({
        status: 'native callback received',
        message: Crowdin.getString('home')
      });
    })

      // print(Crowdin.localizedStringForKey('details_button'))
      // this.setState({
      //   status: 'native callback received',
      //   message
      // });
    // Crowdin.sampleMethod('Testing', 123, (message) => {
    //   this.setState({
    //     status: 'native callback received',
    //     message
    //   });
    // });
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆Crowdin example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>

        <Button
            onPress={() => {
              this.setState({ androidMessage: Crowdin.getString('home') });
            }}
            title={"Get Text from Android!"}
          />

        <Text style={styles.instructions}>{this.state.androidMessage}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
